import { MapPin, Calendar, Building2, Download } from "lucide-react";
import { localityName, cityName, micromarket, reportDate, polygonThumbnail } from "@/lib/reportData";
import { isPrintMode } from "@/lib/print";

const ReportHeader = () => {
  const printMode = isPrintMode();

  const onDownloadPdf = async () => {
  try {
    const locality = encodeURIComponent(localityName || "Locality");
    const resp = await fetch(`http://localhost:8787/api/pdf?locality=${locality}`, {
      method: "GET",
    });

    if (!resp.ok) throw new Error(`PDF download failed: ${resp.status}`);

    const blob = await resp.blob();
    const url = window.URL.createObjectURL(blob);

    const a = document.createElement("a");
    a.href = url;
    a.download = `${localityName || "Locality"} Locality Report.pdf`;
    document.body.appendChild(a);
    a.click();
    a.remove();

    window.URL.revokeObjectURL(url);
  } catch (e) {
    console.error(e);
    alert("Failed to download PDF. Check the PDF server logs.");
  }
};

  return (
    <section className="relative overflow-hidden rounded-2xl sy-card-shadow-lg">
      <div className="sy-gradient px-5 py-8 md:px-12 md:py-14">
        <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-6 md:gap-8">
          <div className="space-y-3 md:space-y-4">
            <div className="flex items-center gap-3 flex-wrap">
              <div className="inline-flex items-center gap-2 rounded-full bg-primary-foreground/20 px-3 py-1 md:px-4 md:py-1.5 text-xs md:text-sm font-medium text-primary-foreground backdrop-blur-sm">
                <Building2 className="h-4 w-4" />
                <span>Locality Report</span>
              </div>

              {/* Download CTA only in normal mode */}
              {!printMode ? (
                <button
                  onClick={onDownloadPdf}
                  className="inline-flex items-center gap-2 rounded-full bg-primary-foreground text-primary px-3 py-1 md:px-4 md:py-1.5 text-xs md:text-sm font-semibold hover:opacity-90 transition"
                >
                  <Download className="h-4 w-4" />
                  Download PDF
                </button>
              ) : null}
            </div>

            <h1 className="font-display text-3xl md:text-5xl font-extrabold text-primary-foreground leading-tight">
              {localityName}
            </h1>

            <div className="flex flex-wrap items-center gap-4 text-primary-foreground/90">
              <span className="flex items-center gap-1.5">
                <MapPin className="h-4 w-4" />
                {cityName} | {micromarket}
              </span>
              <span className="flex items-center gap-1.5">
                <Calendar className="h-4 w-4" />
                As of {reportDate}
              </span>
            </div>
          </div>

          <div className="shrink-0 self-center md:self-auto">
            <div className="w-36 h-36 md:w-56 md:h-56 rounded-xl overflow-hidden bg-primary-foreground/10 backdrop-blur-sm border-2 border-primary-foreground/20">
              <img src={polygonThumbnail} alt={`${localityName} map`} className="w-full h-full object-cover" />
            </div>
          </div>
        </div>

        <p className="mt-6 text-xs text-primary-foreground/60">
          Generated by Square Yards — Automated Locality Report Engine
        </p>
      </div>
    </section>
  );
};

export default ReportHeader;