import { useEffect, useMemo } from "react";

import ReportNav from "@/components/report/ReportNav";
import ReportHeader from "@/components/report/ReportHeader";
import ExecutiveSummary from "@/components/report/ExecutiveSummary";
import PriceTrendChart from "@/components/report/PriceTrendChart";
import LiveabilityIndices from "@/components/report/LiveabilityIndices";
import MarketSnapshot from "@/components/report/MarketSnapshot";
import NearbyLocalities from "@/components/report/NearbyLocalities";
import DemandSupply from "@/components/report/DemandSupply";
import PropertyRates from "@/components/report/PropertyRates";
import TopProjects from "@/components/report/TopProjects";
import RegistrationOverview from "@/components/report/RegistrationOverview";
import ReviewsSection from "@/components/report/ReviewsSection";
import LocalityAttributes from "@/components/report/LocalityAttributes";
import { localityName } from "@/lib/reportData";
import { isPrintMode } from "@/lib/print";

const Index = () => {
  const printMode = useMemo(() => isPrintMode(), []);

  // If in printMode, auto-trigger print (user will "Save as PDF")
  useEffect(() => {
    if (!printMode) return;

    // Give charts/fonts a moment to render before printing
    const t = window.setTimeout(() => {
      try {
        document.title = `${localityName} - Locality Report`;
        window.print();
      } catch {
        // ignore
      }
    }, 1200);

    return () => window.clearTimeout(t);
  }, [printMode]);

  return (
    <div className={`min-h-screen ${printMode ? "bg-white" : "bg-background"}`}>
      {/* Hide navigation completely in print mode */}
      {!printMode ? <ReportNav /> : null}

      {/* Main content */}
      <div className={printMode ? "" : "lg:ml-52 pt-24 lg:pt-0"}>
        <div
          className={
            printMode
              ? "mx-auto px-6 py-6 space-y-10"
              : "max-w-5xl mx-auto px-4 md:px-8 py-6 lg:py-8 space-y-10 scroll-smooth"
          }
        >
          <div id="summary" className={printMode ? "" : "scroll-mt-28 lg:scroll-mt-8"}>
            <ReportHeader />
            <div className="mt-8">
              <ExecutiveSummary />
            </div>
          </div>

          <div id="price-trend" className={printMode ? "" : "scroll-mt-28 lg:scroll-mt-8"}>
            <PriceTrendChart />
          </div>

          <div id="liveability" className={printMode ? "" : "scroll-mt-28 lg:scroll-mt-8"}>
            <LiveabilityIndices />
          </div>

          <div id="highlights" className={printMode ? "" : "scroll-mt-28 lg:scroll-mt-8"}>
            <LocalityAttributes />
          </div>

          <div id="market" className={printMode ? "" : "scroll-mt-28 lg:scroll-mt-8"}>
            <MarketSnapshot />
          </div>

          <div id="nearby" className={printMode ? "" : "scroll-mt-28 lg:scroll-mt-8"}>
            <NearbyLocalities />
          </div>

          <div id="demand-supply" className={printMode ? "" : "scroll-mt-28 lg:scroll-mt-8"}>
            <DemandSupply />
          </div>

          <div id="property-rates" className={printMode ? "" : "scroll-mt-28 lg:scroll-mt-8"}>
            <PropertyRates />
          </div>

          <div id="top-projects" className={printMode ? "" : "scroll-mt-28 lg:scroll-mt-8"}>
            <TopProjects />
          </div>

          <div id="registration" className={printMode ? "" : "scroll-mt-28 lg:scroll-mt-8"}>
            <RegistrationOverview />
          </div>

          <div id="reviews" className={printMode ? "" : "scroll-mt-28 lg:scroll-mt-8"}>
            <ReviewsSection />
          </div>

          <footer className="text-center py-8 border-t border-border">
            <p className="text-xs text-muted-foreground">
              Generated by Square Yards — Automated Locality Report Engine · {localityName}
            </p>
          </footer>
        </div>
      </div>
    </div>
  );
};

export default Index;